### ISSUE TITLE
IOS build Failed 

### ISSUE THREAD

**Issue by hasanKhateb199** [Tap-Payments/gosellSDK-Flutter#39]
build failed for IOS with the follow error 

> Xcode build done.                                           24.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    /Users/hasankhateb/development/flutter/.pub-cache/hosted/pub.dartlang.org/go_sell_sdk_flutter-2.0.9/ios/Classes/SwiftGoSellSdkFlutterPlugin.swift:3:8: error: could not find module 'goSellSDK' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator
    import goSellSDK
           ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
Could not build the application for the simulator.
Error launching application on iPhone 11.
Exited (sigterm)

flutter version "Flutter (Channel stable, 2.5.1, on macOS 11.2.3 20D91 darwin-x64, locale en-JO)"

**Comment by hasanKhateb199** [comment]
5 days still now answer?
why?

**Comment by eslam-elswesy** [comment]
the error need to be solved as soon as

**Comment by wa11breaker** [comment]
Any update on this?

**Comment by kareemTap** [comment]
@hasanKhateb199 Can you please upgrade to our latest version and let us know if the issue has been fixed?

**Comment by hasanKhateb199** [comment]
@kareemTap it's working now Thanks

**Comment by ObaidaKhater** [comment]
@hasanKhateb199 
please can you tell me how can i solve problem
