### ISSUE TITLE
Failed to decrypt RSA encryption, please check your encryption

### ISSUE THREAD

**Issue by Yazan99sh** [Tap-Payments/gosellSDK-Flutter#44]
When I tried to use the sdk on production I got this error 
I entered mada card  
{"errors":[{"code":"1103","error":"Required_inputs_invalid","description":"Failed to decrypt RSA encryption, please check your encryption"}]}

**Comment by vipul8815** [comment]
i m also getting same error

**Comment by krishna-pietech** [comment]
> When I tried to use the sdk on production I got this error I entered mada card {"errors":[{"code":"1103","error":"Required_inputs_invalid","description":"Failed to decrypt RSA encryption, please check your encryption"}]}

@Yazan99sh why this is closed. Have you found the solution. Currently we are blocked with this issue

**Comment by Yazan99sh** [comment]
@vipul8815 @krishna-pietech 
Yes it's been solved for me ,Try to rise the minimum amount of payment go for 3 sar at least.
