### ISSUE TITLE
Issue with CardIO Bitcode After Updating to Xcode 16

### ISSUE THREAD

**Issue by ahmednafea-HT** [Tap-Payments/gosellSDK-Flutter#65]
After upgrading to Xcode 16, I encountered a problem with the CardIO framework. The issue arises during the IPA upload process to TestFlight, where the validation fails due to the presence of bitcode in the CardIO framework. The error message displayed is:

"Asset validation failed. Invalid Executable. The executable 'Runner.app/Frameworks/CardIO.framework/CardIO' contains bitcode."

This prevents the successful upload of the IPA to TestFlight.
![Screenshot 2024-09-19 at 7 04 25 PM](https://github.com/user-attachments/assets/d494d1c2-7605-48f1-90a0-f08fe9789fc6)

**Comment by Abouassi98** [comment]
Iam facing same issue
