### ISSUE TITLE
Swift Compiler Error in TapNibInputView: '@objc' property requires iOS 13.0

### ISSUE THREAD

**Issue by ZameerHaider** [Tap-Payments/gosellSDK-Flutter#67]
I encountered a  error while using the gosellSDK-Flutter library in both the provided example project and my own Flutter project. The error message is as follows:

'@objc' property in extension of subclass of 'TapNibInputView' requires iOS 13.0.0
/Users/zamir/Downloads/gosellSDK-Flutter-master/example/ios/Pods/TapResponderChainInputViewV2/TapResponderChainInputViewV2/TapResponderChainInputViewV2/Source/TapResponderChainInputView.swift:197:15
This issue occurs on Flutter version 3.24.3 and Cocoapods version 1.16.1.

**Comment by nadiraziz** [comment]
Swift Compiler Error (Xcode): '@objc' property in extension of subclass of 'TapNibInputView' requires iOS 13.0.0
/Users/lyve/projects/lyveorder-grocery-app/src/ios/Pods/TapResponderChainInputViewV2/TapResponderChainInputViewV2/TapResponderChainInputViewV2/Source/TapResponderChainInputView.swift:197:15

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
Same issue I am facing

**Comment by ZameerHaider** [comment]
go_sell_sdk_flutter: ^2.4.10
Flutter 3.24.3
Cocoapods version 1.16.1
macos 15.0.1 (24A348)

issue is still there

**Comment by ZameerHaider** [comment]
Update command lines tools to latest version and the issue will be resolved with go_sell_sdk_flutter: ^2.4.10
