### ISSUE TITLE
Non 3D secure transactions are not allowed

### ISSUE THREAD

**Issue by MavericMujeeb** [Tap-Payments/gosellSDK-Flutter#7]
Hi, 

I am getting below error 
{ "errors": [{  "code": "1109", "description": "Non 3D secure transactions are not allowed"}]}

**Comment by HaithamSheshtawy** [comment]
Make sure is 3D Secure is enabled for your account
review this with tap support

**Comment by MavericMujeeb** [comment]
> Make sure is 3D Secure is enabled for your account
> review this with tap support

Thanks, worked
