### ISSUE TITLE
why plugin allow only one type card 

### ISSUE THREAD

**Issue by vipul8815** [Tap-Payments/gosellSDK-Flutter#9]
// Allowed cards
        allowedCadTypes: CardType.CREDIT,
       or
 allowedCadTypes: CardType.DEBIT,

**Comment by HaithamSheshtawy** [comment]
this actually define the accepted card types either credit or debit and by default both are allowed.
So, if u wanna to allow only credit card use allowedCadTypes: CardType.CREDIT
